### ISSUE TITLE
Error while importing heightmap

### ISSUE THREAD

**Issue by coma94** [blendit/env#49]
In #18, with blender 2.77:

```
Aligning Nodes
Info: Added 1 Image Plane(s)
Traceback (most recent call last):
  File "/home/et/ECOLE/M1/S1/PI/env/src/blender/interface.py", line 76, in execute
    a.create_terrain(scn["path"], scn["res"])
  File "/home/et/ECOLE/M1/S1/PI/env/src/blender/blend_environment.py", line 33, in create_terrain
    bpy.context.object.modifiers["Displace"].texture = bpy.data.textures[image]
KeyError: 'bpy_prop_collection[key]: key "mroad2" not found'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by coma94** [comment]
@rmonat can you check that it works on you computer too ?

**Comment by rmonat** [comment]
It works. The mountains look a bit less high ?

**Comment by coma94** [comment]
Yes, I don't know why.. 
If it is a problem we can scale a little bit along the axis z.

**Comment by rmonat** [comment]
I think we need to increase a bit             ob.modifiers["Displace"].strength

**Comment by coma94** [comment]
Ok, do this and then close this issue :)
